openapi: 3.0.3
info:
  title: f1Api
  description: f1Api
  version: 1.0.0
servers:
- url: https://ergast.com/api/f1
tags:
- name: seasons
  description: Seasons list
- name: seasonStages
  description: Season stages
- name: drivers
  description: DriversList
paths:
  /{year}.json:
    get:
      tags:
      - seasonStages
      summary: Gets a season stages by year.
      operationId: getSeasonByYear
      parameters:
        - name: year
          in: path
          description: Season Year Stages
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MRD'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /drivers.json:
    get:
      tags:
        - drivers
      summary: Drivers List
      operationId: driversGet
      parameters:
      - name: limit
        in: query
        schema:
          type: string
      - name: offset
        in: query
        schema:
          type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MRD'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /seasons.json:
    get:
      tags:
      - seasons
      summary: Seasons List
      operationId: seasonsGet
      parameters:
      - name: limit
        in: query
        schema:
          type: string
      - name: offset
        in: query
        schema:
          type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MRD'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    MRD:
      type: object
      properties:
        MRData:
          $ref: '#/components/schemas/MRData'
    MRData:
      type: object
      properties:
        total:
          type: string
        SeasonTable:
          $ref: '#/components/schemas/SeasonTable'
        RaceTable:
          $ref: '#/components/schemas/RaceTable'
        DriverTable:
          $ref: '#/components/schemas/DriverTable'
    ErrorModel:
      required:
      - code
      - message
      type: object
      properties:
        message:
          type: string
        code:
          maximum: 600
          minimum: 100
          type: integer
    SeasonTable:
      type: object
      properties:
        Seasons:
          type: array
          items:
            $ref: '#/components/schemas/Season'
    Season:
      type: object
      properties:
        season:
          type: string
        url:
          type: string
    RaceTable:
      type: object
      properties:
        Races:
          type: array
          items:
            $ref: '#/components/schemas/Race'
    Race:
      type: object
      properties:
        round:
          type: string
        url:
          type: string
        raceName:
          type: string
        season:
          type: string
        date:
          type: string
        Circuit:
          $ref: '#/components/schemas/Circuit'
    Circuit:
      type: object
      properties:
        circuitId:
          type: string
        url:
          type: string
        circuitName:
          type: string
        Location:
          $ref: '#/components/schemas/Location'
    Location:
      type: object
      properties:
        lat:
          type: string
        long:
          type: string
        locality:
          type: string
        country:
          type: string
    DriverTable:
      type: object
      properties:
        Drivers:
          type: array
          items:
            $ref: '#/components/schemas/Driver'
    Driver:
      type: object
      properties:
        driverId:
          type: string
        url:
          type: string
        givenName:
          type: string
        familyName:
          type: string
        dateOfBirth:
          type: string
        nationality:
          type: string
            
