//
// Circuit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Circuit: Codable, Hashable {

    public var circuitId: String?
    public var url: String?
    public var circuitName: String?
    public var location: Location?

    public init(circuitId: String? = nil, url: String? = nil, circuitName: String? = nil, location: Location? = nil) {
        self.circuitId = circuitId
        self.url = url
        self.circuitName = circuitName
        self.location = location
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case circuitId
        case url
        case circuitName
        case location = "Location"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(circuitId, forKey: .circuitId)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(circuitName, forKey: .circuitName)
        try container.encodeIfPresent(location, forKey: .location)
    }



}
