//
// Driver.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Driver: Codable, Hashable {

    public var driverId: String?
    public var url: String?
    public var givenName: String?
    public var familyName: String?
    public var dateOfBirth: String?
    public var nationality: String?

    public init(driverId: String? = nil, url: String? = nil, givenName: String? = nil, familyName: String? = nil, dateOfBirth: String? = nil, nationality: String? = nil) {
        self.driverId = driverId
        self.url = url
        self.givenName = givenName
        self.familyName = familyName
        self.dateOfBirth = dateOfBirth
        self.nationality = nationality
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case driverId
        case url
        case givenName
        case familyName
        case dateOfBirth
        case nationality
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(driverId, forKey: .driverId)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(givenName, forKey: .givenName)
        try container.encodeIfPresent(familyName, forKey: .familyName)
        try container.encodeIfPresent(dateOfBirth, forKey: .dateOfBirth)
        try container.encodeIfPresent(nationality, forKey: .nationality)
    }



}
