//
// DriverTable.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct DriverTable: Codable, Hashable {

    public var drivers: [Driver]?

    public init(drivers: [Driver]? = nil) {
        self.drivers = drivers
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case drivers = "Drivers"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(drivers, forKey: .drivers)
    }



}
