//
// Location.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Location: Codable, Hashable {

    public var lat: String?
    public var long: String?
    public var locality: String?
    public var country: String?

    public init(lat: String? = nil, long: String? = nil, locality: String? = nil, country: String? = nil) {
        self.lat = lat
        self.long = long
        self.locality = locality
        self.country = country
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lat
        case long
        case locality
        case country
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lat, forKey: .lat)
        try container.encodeIfPresent(long, forKey: .long)
        try container.encodeIfPresent(locality, forKey: .locality)
        try container.encodeIfPresent(country, forKey: .country)
    }



}
