//
// RaceTable.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct RaceTable: Codable, Hashable {

    public var races: [Race]?

    public init(races: [Race]? = nil) {
        self.races = races
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case races = "Races"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(races, forKey: .races)
    }



}
