//
// MRD.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct MRD: Codable, Hashable {

    public var mRData: MRData?

    public init(mRData: MRData? = nil) {
        self.mRData = mRData
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mRData = "MRData"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mRData, forKey: .mRData)
    }



}
