//
// MRData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct MRData: Codable, Hashable {

    public var total: String?
    public var seasonTable: SeasonTable?

    public init(total: String? = nil, seasonTable: SeasonTable? = nil) {
        self.total = total
        self.seasonTable = seasonTable
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case seasonTable = "SeasonTable"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(seasonTable, forKey: .seasonTable)
    }



}
