//
// SeasonTable.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SeasonTable: Codable, Hashable {

    public var seasons: [Season]?

    public init(seasons: [Season]? = nil) {
        self.seasons = seasons
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case seasons = "Seasons"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(seasons, forKey: .seasons)
    }



}
