//
// Season.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Season: Codable, Hashable {

    public var season: String?
    public var url: String?

    public init(season: String? = nil, url: String? = nil) {
        self.season = season
        self.url = url
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case season
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(season, forKey: .season)
        try container.encodeIfPresent(url, forKey: .url)
    }



}
